// Generated by CoffeeScript 1.6.2
var cancelUpload, handleUpload, request;

request = new XMLHttpRequest();

cancelUpload = function() {
  return request.abort();
};

handleUpload = function(evt) {
  var data, fileInput;

  evt.preventDefault();
  evt.stopPropagation();
  fileInput = document.getElementById('file');
  data = new FormData();
  data.append('file', fileInput.files[0]);
  request.upload.addEventListener('progress', function(evt) {
    var percent, progress;

    if (evt.lengthComputable) {
      percent = evt.loaded / evt.total;
      progress = document.getElementById('upload_progress');
      while (progress.hasChildNodes()) {
        progress.removeChild(progress.firstChild);
      }
      return progress.appendChild(document.createTextNode(Math.round(percent * 100) + ' %'));
    }
  });
  request.upload.addEventListener('load', function(evt) {
    return document.getElementById('upload_progress').style.display = 'none';
  });
  request.upload.addEventListener('error', function(evt) {
    return alert('Upload Failed');
  });
  request.open('POST', 'index.php');
  request.setRequestHeader('Cache-Control', 'no-cache');
  document.getElementById('upload_progress').style.display = 'block';
  return request.send(data);
};

window.addEventListener('load', function(evt) {
  var cancel, submit;

  submit = document.getElementById('submit');
  cancel = document.getElementById('cancel');
  submit.addEventListener('click', handleUpload);
  return cancel.addEventListener('click', cancelUpload);
});
